
components:
  proxy:
    disabled: true

  wsManagerBridge:
    disabled: true

  server:
    disabled: true

  messagebus:
    disabled: true

  dashboard:
    disabled: true

  dbMigrations:
    disabled: true

  db:
    autoMigrate: false

  imageBuilder:
    disabled: true

minio:
  enabled: false

mysql:
  enabled: false

