# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: jaeger
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: jaeger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jaeger-psp
