packages:
  - name: plugin
    type: generic
    srcs:
      - "**/*.kt"
      - "build.gradle.kts"
      - "gradle.properties"
      - "gradle/wrapper/*"
      - "gradlew"
      - "settings.gradle.kts"
    env:
      - JAVA_HOME=/home/gitpod/.sdkman/candidates/java/current
    config:
      commands:
        - ["./gradlew", "buildPlugin"]
