packages:
  - name: plugin
    type: generic
    srcs:
      - "**/*.kt"
      - "build.gradle.kts"
      - "gradle.properties"
      - "gradle/wrapper/*"
      - "gradlew"
      - "settings.gradle.kts"
    env:
      - JAVA_HOME=/home/gitpod/.sdkman/candidates/java/current
    deps:
      - components/gitpod-protocol/java:lib
      - components/supervisor-api/java:lib
    config:
      commands:
        - ["./gradlew", "-PsupervisorApiProjectPath=components-supervisor-api-java--lib/", "-PgitpodProtocolProjectPath=components-gitpod-protocol-java--lib/", "buildPlugin"]
