packages:
  - name: docker
    type: docker
    srcs:
      - node-daemon.sh
      - post-delete-cleanup.sh
    argdeps:
      - imageRepoBase
    config:
      dockerfile: Dockerfile
      image:
        - ${imageRepoBase}/node-daemon:${version}
